AC_PROD =
(DESCRIPTION =
  (TRANSPORT_CONNECT_TIMEOUT=3000)
  (CONNECT_TIMEOUT=120)
  (RETRY_COUNT=20)
  (RETRY_DELAY=3)
  (FAILOVER=ON)
  (ADDRESS_LIST=
     (LOAD_BALANCE=on)(LOAD_BALANCE=YES)
     (ADDRESS=(PROTOCOL=TCP)(HOST=10.0.10.220)(PORT=1523))
     (ADDRESS=(PROTOCOL=TCP)(HOST=10.20.10.224)(PORT=1523))
  )
  (CONNECT_DATA=
     (SERVICE_NAME=BDSRMAC.snbdvcnsrmadmin.vcnsrmadmin.oraclevcn.com)
  )
 )

AC_PROD =
 (DESCRIPTION =
  (CONNECT_TIMEOUT= 15)
  (RETRY_COUNT=50
  )(RETRY_DELAY=3)
  (ADDRESS_LIST =
    (LOAD_BALANCE=on)
    (ADDRESS = (PROTOCOL=TCP)(HOST=10.0.10.220) (PORT=1523) )
  )
  (ADDRESS_LIST =
    (LOAD_BALANCE=on)
    (ADDRESS = (PROTOCOL=TCP)(HOST=10.20.10.224)(PORT=1523) )
  )
  (CONNECT_DATA=
     (SERVICE_NAME = BDSRMAC.snbdvcnsrmadmin.vcnsrmadmin.oraclevcn.com))
 )