version: '3.1'
services:
  web:
    image: odoo:17
    command: ["odoo", "-d", "odoodb", "-i", "base", "--without-demo=all"]
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: "db"
      USER: "odoo"
      PASSWORD: "odoo"
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: "odoodb"
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "odoo"
