version: '3.1'
services:
  web:
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8069 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    image: odoo:17
    command: ["odoo", "-d", "odoodb", "-i", "base", "--without-demo=all"]
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: "db"
      USER: "odoo"
      PASSWORD: "odoo"
  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 3
    security_opt:
      - no-new-privileges
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    networks:
      - mynetwork
    image: postgres:13
    environment:
      POSTGRES_DB: "odoodb"
      POSTGRES_USER: "odoo"
      POSTGRES_PASSWORD: "odoo"