apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: ODOO_URL
              value: {{ .Values.env.ODOO_URL }}
            - name: ODOO_DB
              value: {{ .Values.env.ODOO_DB }}
            - name: ODOO_USERNAME
              value: {{ .Values.env.ODOO_USERNAME }}
            - name: ODOO_PASSWORD
              value: {{ .Values.env.ODOO_PASSWORD }}
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
          securityContext:
            allowPrivilegeEscalation: false
            automountServiceAccountToken: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 10001
            runAsNonRoot: true
            runAsUser: 10001
            securityContext:
              type: Pod
            seccompProfile:
              type: RuntimeDefault